FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 4200 for the development server
EXPOSE 4200

# Start the Angular development server with the host set to 0.0.0.0 to make it accessible outside the container
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--disable-host-check"]