FROM node:18

WORKDIR /app

# Copy package files and install dependencies first for caching benefits
COPY package*.json ./
# Clean install without relying on package-lock.json
RUN npm install --force

# Copy the rest of your application code
COPY . .


# Expose the Angular dev server port
EXPOSE 4200

# Start the Angular dev server with options to listen on all interfaces
CMD ["npm", "start"]