version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - node_modules:/app/node_modules
      - angular_cache:/app/.angular/cache
      - ./frontend:/app:cached
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/talentlink
      - JWT_SECRET=fdsjklafjdlkajfkldasjfaldksjlkfads
      - AUTH0_ISSUER=dev-zxuicoohweme0r55.us.auth0.com
      - AUTH0_AUDIENCE=https://dev-zxuicoohweme0r55.us.auth0.com/api/v2/
    command: npm start

  # API Gateway - Entry point for all API requests
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/talentlink
      - USER_SERVICE_URL=http://user-service:3001
    depends_on:
      - mongodb
      - user-service

  # User Service - Initial service to handle authentication
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
    environment:
    - NODE_ENV=development
    - PORT=3001
    - MONGODB_URI=mongodb://mongodb:27017/talentlink
    - AUTH0_DOMAIN=dev-zxuicoohweme0r55.us.auth0.com
    - AUTH0_AUDIENCE=https://api.talentlink.com
    - AUTH0_CLIENT_ID=773kVrTY9AIUUAhL8sptPJccA9lkHszI
    - AUTH0_CLIENT_SECRET=v_e1gClNsSKg7SXQGhdkQQflT6Juj8R30UdcoLfYHBty3Gd157snDsQpxipcfRCr
    - AUTH0_ISSUER_BASE_URL=https://dev-zxuicoohweme0r55.us.auth0.com
    depends_on:
      - mongodb

  # MongoDB - Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=talentlink
      
volumes:
  mongodb-data:
  node_modules:
  angular_cache:
