version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - node_modules:/app/node_modules
      - angular_cache:/app/.angular/cache
      - ./frontend:/app:cached
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=fdsjklafjdlkajfkldasjfaldksjlkfads
      - AUTH0_ISSUER=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    command: npm start

  payment-service:
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend/payment-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
    depends_on:
      - mongodb

  # API Gateway - Entry point for all API requests
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
    depends_on:
      - mongodb
      - user-service

  # User Service - Initial service to handle authentication
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
    environment:
    - NODE_ENV=development
    - PORT=3001
    - MONGODB_URI=${MONGODB_URI}
    - AUTH0_DOMAIN=${AUTH0_DOMAIN}
    - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
    - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
    depends_on:
      - mongodb

  # MongoDB - Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=talentlink
      
volumes:
  mongodb-data:
  node_modules:
  angular_cache:
