FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 3002
EXPOSE 3004

# Start the application in development mode
CMD ["sh", "-c", "npm install && npm run dev"]
